using Nostos.Core.Abstractions;
using Nostos.Core.Localization;
using Nostos.Tweaks.Declarative;

namespace Nostos.App.Localization;

/// <summary>
/// The translated names for things the catalog describes: categories, groups, and the words on
/// a row's badges.
///
/// Every one of these has an English original that lives somewhere else and stays there. A
/// category's name belongs with the category, where the CLI and the profile format can both
/// reach it; a risk level belongs with the enum. This asks only whether somebody has written a
/// German version, and hands back the English when nobody has.
///
/// That is why every lookup here goes through <see cref="Strings.GetOr"/> rather than
/// <see cref="Strings.Get"/>: a missing key must show the English word, not the key. A catalog
/// row reading "risk.moderate" would be worse than one reading "moderate".
/// </summary>
internal static class CatalogText
{
    /// <summary>A tweak's title, translated if somebody has written one.</summary>
    public static string TweakTitle(string id, string english)
        => Translation(id)?.Title ?? english;

    /// <summary>A tweak's summary, translated if somebody has written one.</summary>
    public static string TweakSummary(string id, string english)
        => Translation(id)?.Summary ?? english;

    /// <summary>
    /// A choice's title, from the tweak's own translation or from a shared one.
    ///
    /// The shared key is what makes the 35 service tweaks bearable. Every one of them offers
    /// the same choice, generated by the same class, so translating it per tweak would mean
    /// writing the same four paragraphs thirty-five times and keeping them in step forever.
    /// A choice id is shared vocabulary, so it gets a shared key: <c>choice.startup.title</c>.
    ///
    /// A tweak's own translation still wins, so a service that needs to say something
    /// different can.
    /// </summary>
    public static string ChoiceTitle(string tweakId, string choiceId, string english)
        => Choice(tweakId, choiceId)?.Title ?? Strings.GetOr($"choice.{choiceId}.title", english);

    public static string ChoiceDescription(string tweakId, string choiceId, string english)
        => Choice(tweakId, choiceId)?.Description
           ?? Strings.GetOr($"choice.{choiceId}.description", english);

    public static string OptionTitle(string tweakId, string choiceId, string optionId, string english)
        => Option(tweakId, choiceId, optionId)?.Title
           ?? Strings.GetOr($"choice.{choiceId}.{optionId}.title", english);

    public static string OptionDescription(string tweakId, string choiceId, string optionId, string english)
        => Option(tweakId, choiceId, optionId)?.Description
           ?? Strings.GetOr($"choice.{choiceId}.{optionId}.description", english);

    private static TweakTranslation? Translation(string id)
        => CatalogTranslations.Find(Strings.Language, id);

    private static ChoiceTranslation? Choice(string tweakId, string choiceId)
        => Translation(tweakId)?.Choices is { } choices
           && choices.TryGetValue(choiceId, out var choice)
            ? choice
            : null;

    private static OptionTranslation? Option(string tweakId, string choiceId, string optionId)
        => Choice(tweakId, choiceId)?.Options is { } options
           && options.TryGetValue(optionId, out var option)
            ? option
            : null;

    /// <summary>"Leistung" for "performance".</summary>
    public static string CategoryName(string id)
        => Strings.GetOr($"category.{id}.name", TweakCategories.NameOf(id));

    /// <summary>What filing a tweak in this category claims about it.</summary>
    public static string? CategoryPromise(string id)
        => TweakCategories.Find(id) is { } category
            ? Strings.GetOr($"category.{id}.promise", category.Promise)
            : null;

    public static string GroupName(TweakGroup group)
        => Strings.GetOr($"group.{Slug(group)}.name", TweakCategories.NameOfGroup(group));

    public static string GroupDescription(TweakGroup group)
        => Strings.GetOr($"group.{Slug(group)}.description", TweakCategories.DescriptionOfGroup(group));

    public static string Risk(Risk risk)
        => Strings.GetOr($"risk.{Slug(risk)}", risk.ToString().ToLowerInvariant());

    /// <summary>
    /// The heading over a run of rows that share a risk level, and the line under it.
    ///
    /// Separate from <see cref="Risk"/>, which is the word on a row's badge. A badge is read
    /// alongside a title and wants to be one lower-case word; a heading is read on its own and
    /// wants to say what the level actually means, because "Moderate" tells somebody nothing
    /// about whether to click the thing underneath it.
    /// </summary>
    public static string RiskBandName(Risk risk)
        => Strings.GetOr($"band.risk.{Slug(risk)}.name", risk.ToString());

    public static string RiskBandDescription(Risk risk)
        => Strings.GetOr($"band.risk.{Slug(risk)}.description", "");

    public static string Evidence(Evidence evidence)
        => Strings.GetOr($"evidence.{Slug(evidence)}", evidence.ToString().ToLowerInvariant());

    public static string Scope(TweakScope scope)
        => Strings.GetOr($"scope.{Slug(scope)}", scope.ToString().ToLowerInvariant());

    /// <summary>The ON/OFF badge.</summary>
    public static string State(bool applied)
        => applied ? Strings.GetOr("state.on", "ON") : Strings.GetOr("state.off", "OFF");

    private static string Slug<T>(T value) where T : notnull
        => value.ToString()!.ToLowerInvariant();
}
